create table ORDERS(
ID NUMBER (*,0) NOT NULL,
AMOUNT NUMBER (8,2) NOT NULL,
ORDEN_DATE DATE,
CUSTOMER_ID NUMBER (*,0) NOT NULL


)
CREATE TABLE CUSTOMERS(
ID NUMBER (*,0) NOT NULL,
NAME VARCHAR2 (255 BYTE) NOT NULL,
CITY VARCHAR2 (255),
GRADE NUMBER (*,0) NOT NULL,
SALEMAN_ID NUMBER(*,0)
)
CREATE TABLE SALEMAN(
ID NUMBER (*,0),
NAME VARCHAR2 (255),
COMMISSION NUMBER(5,2)
)
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PK PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID);
ALTER TABLE SALEMAN ADD CONSTRAINT SALEMAN_PK PRIMARY KEY (ID);

ALTER TABLE ORDERS ADD CONSTRAINT CUSTOMER_ORDER_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES SALESMAN (ID);
ALTER TABLE ORDERS ADD CONSTRAINT SALESMAN_ORDER_FK FOREIGN KEY (PROJECT_ID) REFERENCES SALESMAN (ID);
ALTER TABLE SALESMAN ADD CONSTRAINT SALESMAN_PK FOREIGN KEY (MANAGER_ID) REFERENCES CUSTOMERS (ID);
ALTER TABLE CUSTOMERS ADD CONSTRAINT SALESMAN_FK FOREIGN KEY (MANAGER_ID) REFERENCES ORDERS (ID);








  DROP TABLE ORDERS;
   
   